### ISSUE TITLE
MySQL Error with PDO::ATTR_EMULATE_PREPARES and Criteria::BINARY_ALL

### ISSUE THREAD

**Issue by wollanup** [propelorm/Propel2#1192]
I recently add attribute PDO::ATTR_EMULATE_PREPARES to my connection to get benefit of SQL types in query result (without this, all integer results are strings)

but now i'm facing this issue :

mysql client : `mysqlnd 5.0.12-dev`
php : `7.0.4-7ubuntu2`
propel version : last via composer (dev-master 9e4eb90 on 2016-05-24)

propel.yml : 

```
propel:
    database:
        connections:
            default:              
                adapter: mysql                   
                attributes:
                    ATTR_EMULATE_PREPARES: false
```

query : 
`EntityQuery->create->filterByBinaryField(3, Criteria::BINARY_ALL);`

result:

```
Propel\Runtime\Exception\PropelException
Unable to execute SELECT statement [SELECT * AS FROM table WHERE table.binary & :p1 = :p1]
File: /var/www/.../vendor/propel/propel/src/Propel/Runtime/ActiveQuery/Criteria.php
Line: 2650

Previous exception
Type: PDOException
Code:HY093
Message: SQLSTATE[HY093]: Invalid parameter number
File: /var/www/.../vendor/propel/propel/src/Propel/Runtime/Adapter/Pdo/PdoStatement.php
Line:57
Trace :
#0 /var/www/.../vendor/propel/propel/src/Propel/Runtime/Adapter/Pdo/PdoStatement.php(57): PDOStatement->execute(NULL)
#1 /var/www/.../vendor/propel/propel/src/Propel/Runtime/Connection/StatementWrapper.php(194): Propel\Runtime\Adapter\Pdo\PdoStatement->execute(NULL)
#2 /var/www/.../vendor/propel/propel/src/Propel/Runtime/ActiveQuery/Criteria.php(2644): Propel\Runtime\Connection\StatementWrapper->execute()
#3 /var/www/.../vendor/propel/propel/src/Propel/Runtime/ActiveQuery/ModelCriteria.php(1988): Propel\Runtime\ActiveQuery\Criteria->doSelect(Object(Propel\Runtime\Connection\DebugPDO))
#4 /var/www/.../vendor/propel/propel/src/Propel/Runtime/ActiveQuery/ModelCriteria.php(1024): Propel\Runtime\ActiveQuery\ModelCriteria->doSelect(Object(Propel\Runtime\Connection\DebugPDO))
```

The same query without ATTR_EMULATE_PREPARES works fine.

in [Propel/Runtime/ActiveQuery/Criterion/BinaryCriterion.php:48](https://github.com/propelorm/Propel2/blob/master/src/Propel/Runtime/ActiveQuery/Criterion/BinaryCriterion.php) we have :
`$sb .= $field . ' & ' . $bindParam . ' = ' . $bindParam;`
so, in final query we have 2 parameters (`:p1 = :p1`) bound only once. Maybe the native prepare method excepts two differents binds ?

If someone knows how to preserve SQL types in results without ATTR_EMULATE_PREPARES, let me know please :)

**Comment by akashjarad** [comment]
+1

**Comment by dereuromark** [comment]
Is someone able to make a PR here with suggested changes?

**Comment by wollanup** [comment]
`\Propel\Runtime\ActiveQuery\Criterion\BinaryCriterion::appendPsForUniqueClauseTo`

```php
    protected function appendPsForUniqueClauseTo(&$sb, array &$params)
    {
        if ($this->value !== null) {
            $params[] = ['table' => $this->realtable, 'column' => $this->column, 'value' => $this->value];
            $bindParam = ':p' . count($params);
            $field = ($this->table === null) ? $this->column : $this->table . '.' . $this->column;

            if ($this->comparison === Criteria::BINARY_ALL) {
/* MODIFIED PART */
                // With ATTR_EMULATE_PREPARES => false, we can't have two identical params, so let's add another param
                // https://github.com/propelorm/Propel2/issues/1192
                $params[] = ['table' => $this->realtable, 'column' => $this->column, 'value' => $this->value];
                $bindParam2 = ':p' . count($params);
                $sb .= $field . ' & ' . $bindParam . ' = ' . $bindParam2;
/* WAS */
//              $sb .= $field . ' & ' . $bindParam . ' = ' . $bindParam;
/* END */
            } else {
                $sb .= $field . ' & ' . $bindParam . ' = 0';
            }
        } else {
            $sb .= $this->comparison === Criteria::BINARY_ALL ? '1<>1' : '1=1';
        }
    }

```
Just added another param, it seems to do the job,  but I will wait fore some CI jobs to pass on real apps
I should be able to make a PR, but it can be tricky to test. I didn't play with propel tests since a loooong time :)

**Comment by dereuromark** [comment]
Give it a try :) We will see how it goes.

**Comment by dereuromark** [comment]
PR open for this
