### ISSUE TITLE
Deep copying not working correctly

### ISSUE THREAD

**Issue by shaymargolis** [propelorm/Propel2#1264]
Can't get deep copying with one-to-one relationship work like needed. Getting this error:
```
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'' in /vendor/propel/propel/src/Propel/Runtime/Adapter/Pdo/PdoStatement.php:57
Stack trace:
#0 /vendor/propel/propel/src/Propel/Runtime/Adapter/Pdo/PdoStatement.php(57): PDOStatement->execute(NULL)
#1 /vendor/propel/propel/src/Propel/Runtime/Connection/StatementWrapper.php(194): Propel\Runtime\Adapter\Pdo\PdoStatement->execute(NULL)
#2 /home/sandbox/generated-classes/Base/Book.php(698): Propel\Runtime\Connection\StatementWrapper->execute()
#3 /home/sandbox/generated-classes/Base/Book.php(637): Base\Book->doInsert(Object(Propel\Runtime\Connection\DebugPDO))
#4 /home/sandbox/generated-classes/Base/Book.php(589): Base\Book->doSave(Object(Propel\Runtime\Connection\DebugPDO))
#5 [internal function]: Base\Book->Base\{closure}()
#6 /vendor/propel/propel/src/Propel/Runtime/Connection/TransactionTrait.php(35): call_user_func(Object(Closure))
#7 /home/sandbox/generated-classes/Base/B in /home/sandbox/generated-classes/Base/Book.php on line 701
```

Check out this fiddle (one-to-one): http://sandbox.propelorm.org/2ec88cf
using many-to-one it's working: http://sandbox.propelorm.org/fd7565a

In both cases, it's not working like the example [here](http://propelorm.org/documentation/cookbook/copying-persisted-objects.html), because the Auther object is not copied.

**Comment by marcj** [comment]
`Book` does not have a auto increment at its primary key, so you need to define a different ID after copying. Second fiddle works because you have a auto increment.
