### ISSUE TITLE
MSSQL - Uncaught 'PDOException' - "attribute only supported on PDOStatement object"

### ISSUE THREAD

**Issue by MDT-FGI** [propelorm/Propel2#1271]
Hello,

I set up a project and had it working fine with MySQL. I now wanted to switch it to MSSQL and adjusted all the configs files as described in the documentation. Unfortunately I get the following error:
`Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[IMSSP]: The given attribute is only supported on the PDOStatement object.' in H:\xampp\htdocs\vendor\propel\propel\src\Propel\Runtime\Connection\PdoConnection.php:85 Stack trace: #0 H:\xampp\htdocs\vendor\propel\propel\src\Propel\Runtime\Connection\PdoConnection.php(85): PDO->setAttribute(20, false) #1 H:\xampp\htdocs\vendor\propel\propel\src\Propel\Runtime\Connection\ConnectionWrapper.php(358): Propel\Runtime\Connection\PdoConnection->setAttribute(20, false) #2 H:\xampp\htdocs\vendor\propel\propel\src\Propel\Runtime\Connection\ConnectionFactory.php(58): Propel\Runtime\Connection\ConnectionWrapper->setAttribute('ATTR_EMULATE_PR...', false) #3 H:\xampp\htdocs\vendor\propel\propel\src\Propel\Runtime\Connection\ConnectionManagerSingle.php(76): Propel\Runtime\Connection\ConnectionFactory::create(Array, Object(Propel\Runtime\Adapter\Pdo\MssqlAdapter)) #4 H:\xampp\htdocs\vendor\propel\propel\src\Propel\Runtime\Connection\ConnectionManagerSingle.php(90): Prope in H:\xampp\htdocs\vendor\propel\propel\src\Propel\Runtime\Connection\PdoConnection.php on line 85`

`<?php
 
// When you're part of a team, you could want to define a common configuration file and commit it into your VCS. But, of
// course, there can be some properties you don't want to share, e.g. database passwords. Propel helps you and looks for
// a propel.yml.dist file too, merging its properties with propel.yml ones. So you can define shared configuration
// properties in propel.yml.dist, committing it in your VCS, and keep propel.yml as private. The properties loaded from
// propel.yml overwrite the ones with the same name, loaded from propel.yml.dist.
//
// For a complete references see: http://propelorm.org/documentation/reference/configuration-file.html

return [
    'propel' => [
        'paths' => [
            // The directory where Propel expects to find your `schema.xml` file.
            'schemaDir' => 'H:/xampp/htdocs/vendor',

            // The directory where Propel should output generated object model classes.
            'phpDir' => 'H:/xampp/htdocs/Models',
        ],
        'database' => [
            'connections' => [
                'PMDB_Prod' => [
                    'adapter'    => 'mssql',
                    'classname'  => 'Propel\Runtime\Connection\ConnectionWrapper',
                    'dsn'        => 'sqlsrv:server=xxxxx\xxxxxx;Database=xxxxxxx',
                    'user'       => 'xxxxxxx',
                    'password'   => 'xxxxxxx',
                    'attributes' => []
                ]
            ]
        ],
        'runtime' => [
            'defaultConnection' => 'PMDB_Prod',
            'connections' => ['PMDB_Prod']
        ],
        'generator' => [
            'defaultConnection' => 'PMDB_Prod',
            'connections' => ['PMDB_Prod']
        ]
    ]
];`

Am I doing anything wrong or is this a bug right here?

**Comment by MDT-FGI** [comment]
I tracked this down to the file "propel\src\Propel\Runtime\ActiveQuery\Criteria.php" where the attributes are set to the connection.

A quick'n'dirty workaround looks like this:
Line 60:
>                 if ($option == "ATTR_EMULATE_PREPARES" || $option == "ATTR_TIMEOUT")
>                 {
>                     continue;
>                 }
>                 
>                 $connection->setAttribute($option, $value);

Of course this is not a solution and just for testing purpose...

**Comment by mhaisley** [comment]
This is a bug I have experienced as well.  I have a similar but different ugly fix.  I'm not sure the best way to resolve...

**Comment by dereuromark** [comment]
Is someone able to make a PR here with suggested changes?
