### ISSUE TITLE
field name "key" cause error

### ISSUE THREAD

**Issue by deckyfx** [propelorm/Propel2#1331]
I have this schema
```
...
<table name="configs" idMethod="native" phpName="Config" namespace="">
    <column name="id" phpName="Id" type="INTEGER" primaryKey="true" autoIncrement="true" required="true"/>
    <column name="key" phpName="Key" type="VARCHAR" size="255" defaultValue=""/>
    <column name="value" phpName="Value" type="LONGVARCHAR"/>
    <column name="type" phpName="Type" type="CHAR" sqlType="enum('string','int','double','boolean')"/>
    <column name="enabled" phpName="Enabled" type="BOOLEAN"/>
    <behavior name="timestampable" />
    <vendor type="mysql">
      <parameter name="Engine" value="InnoDB"/>
    </vendor>
  </table>
...
```

when executing insert, it throw error like this
```
<b>Fatal error</b>:  Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'key, value, type, enabled, created_at, updated_at) VALUES (NULL, 'A', 'A', 'stri' at line 1' in {PROJECT_PATH}/vendor/propel/propel/src/Propel/Runtime/Adapter/Pdo/PdoStatement.php:57
Stack trace:
#0 {PROJECT_PATH}/vendor/propel/propel/src/Propel/Runtime/Adapter/Pdo/PdoStatement.php(57): PDOStatement-&gt;execute(NULL)
#1 {PROJECT_PATH}/vendor/propel/propel/src/Propel/Runtime/Connection/StatementWrapper.php(194): Propel\Runtime\Adapter\Pdo\PdoStatement-&gt;execute(NULL)
#2 {PROJECT_PATH}/schema/Models/Base/Config.php(948): Propel\Runtime\Connection\StatementWrapper-&gt;execute()
#3 {PROJECT_PATH}/schema/Models/Base/Config.php(858): Models\Base\Config-&gt;doInsert(Ob in <b>{PROJECT_PATH}/schema/Models/Base/Config.php</b> on line <b>951</b><br />
```

after fiddling it , i figure out that the Pdo generate the following queries

```
INSERT INTO configs (id, key, value, type, enabled, created_at, updated_at) VALUES (:p0, :p1, :p2, :p3, :p4, :p5, :p6)
```

i tried to executed it in mysql workbench, the sql return error because field name key is reserved, yet executing this is work

```
INSERT INTO configs (id, configs.key, value, type, enabled, created_at, updated_at) VALUES (:p0, :p1, :p2, :p3, :p4, :p5, :p6)
```

so i think all query build should use absolute path, or maybe propel already could do this with some configuration?

**Comment by marcj** [comment]
`<table name="configs" idMethod="native" phpName="Config" identifierQuoting="true">`
http://propelorm.org/documentation/reference/schema.html#table-attributes
