### ISSUE TITLE
Possible Regression in master

### ISSUE THREAD

**Issue by dereuromark** [propelorm/Propel2#1738]
We did a regression check of this repo master branch with our code.

With the commit of https://github.com/propelorm/Propel2/commit/1797fbb2056824469facd0583e80e5767efbf8f2 inside https://github.com/propelorm/Propel2/pull/1711
it seems that a regression is now introduced with our Spryker code/executionflow.

The execution seems to stop here with errors as
- https://jsoneditoronline.org/#left=cloud.6277578def6a4030b96e9f6d79daa2e6
- https://jsoneditoronline.org/#left=cloud.77fdd71c36a84be08454a7bd455e3150

> [console] [cli] - [2021-05-21T12:25:55.052006+00:00] Zed.CRITICAL: ErrorException - Undefined property: Orm\Zed\Store\Persistence\SpyStoreQuery::$select in "/data/src/Orm/Zed/Store/Persistence/Base/SpyStoreQuery.php::493" {"exception":"[object] (ErrorException(code: 0): Undefined property: Orm\\Zed\\Store\\Persistence\\SpyStoreQuery::$select at /data/src/Orm/Zed/Store/Persistence/Base/SpyStoreQuery.php:493)

> [console] [cli] - [2021-05-21T12:26:37.286220+00:00] application_events.INFO: [async] Failed to handle "MerchantProduct.merchant_product_abstract.publish" for listener "Spryker\Zed\MerchantProductSearch\Communication\Plugin\Publisher\MerchantProduct\MerchantProductSearchWritePublisherPlugin". Exception: "Undefined offset: 4"

cc @mringler

**Comment by mringler** [comment]
Yes, the `ModelCriteria::$select` property is not necessary anymore and was removed.
It looks like you are seeing an error because the property is still referenced in the base model class' `SpyStoreQuery::findPk()` method, which indicates that you did not rebuild your base model files. Can you do that?

I don't think this is regression or a break of backwards compatibility, since updating the base classes is a necessary part of updating Propel.

**Comment by dereuromark** [comment]
You are probably right, we will double check that.
I started in the meantime https://github.com/propelorm/Propel2/pull/1735 which should help to find possible issues by just running smoke integration of the PR/branch on an existing demo implementation.
If it crashes at some point we know that we need to look into this.
What do you think?

**Comment by mringler** [comment]
Sounds interesting. I am curious to see what you find.
Most of my PRs were bugfixes or new functionality, so they should be of no consequence to existing projects. The few that have the potential to impact existing projects should still only show up in rare and very specific situations (like an existing override of a method with an updated signature). Let's see if you run into those in the demo project

**Comment by dereuromark** [comment]
So the above might be resolved, but we encountered a different issue now that blocks further BC check and release.
Our install script cannot even complete anymore using latest master
```
[previous exception] [object] (PDOException(code: 42803): SQLSTATE[42803]: Grouping error: 7 ERROR:  column \"spy_oms_product_reservation.reservation_quantity\" must appear in the GROUP BY clause or be used in an aggregate function

LINE 1: SELECT \"spy_oms_product_reservation\".\"reservation_quantity\" ...

               ^ at /home/travis/build/spryker/suite-nonsplit/vendor/propel/propel/src/Propel/Runtime/Connection/StatementWrapper.php:215)

[stacktrace]

#0 /home/travis/build/spryker/suite-nonsplit/vendor/propel/propel/src/Propel/Runtime/Connection/StatementWrapper.php(215): PDOStatement->execute(NULL)

#1 /home/travis/build/spryker/suite-nonsplit/vendor/propel/propel/src/Propel/Runtime/ActiveQuery/QueryExecutor/AbstractQueryExecutor.php(103): Propel\\Runtime\\Connection\\StatementWrapper->execute()

#2 /home/travis/build/spryker/suite-nonsplit/vendor/propel/propel/src/Propel/Runtime/ActiveQuery/QueryExecutor/SelectQueryExecutor.php(49): Propel\\Runtime\\ActiveQuery\\QueryExecutor\\AbstractQueryExecutor->executeStatement(Object(Propel\\Runtime\\ActiveQuery\\SqlBuilder\\PreparedStatementDto))

#3 /home/travis/build/spryker/suite-nonsplit/vendor/propel/propel/src/Propel/Runtime/ActiveQuery/QueryExecutor/SelectQueryExecutor.php(37): Propel\\Runtime\\ActiveQuery\\QueryExecutor\\SelectQueryExecutor->runSelect()

#4 /home/travis/build/spryker/suite-nonsplit/vendor/propel/propel/src/Propel/Runtime/ActiveQuery/Criteria.php(2322): Propel\\Runtime\\ActiveQuery\\QueryExecutor\\SelectQueryExecutor::execute(Object(Orm\\Zed\\Oms\\Persistence\\SpyOmsProductReservationQuery), Object(Propel\\Runtime\\Connection\\ConnectionWrapper))

#5 /home/travis/build/spryker/suite-nonsplit/vendor/propel/propel/src/Propel/Runtime/ActiveQuery/ModelCriteria.php(2208): Propel\\Runtime\\ActiveQuery\\Criteria->doSelect(Object(Propel\\Runtime\\Connection\\ConnectionWrapper))

#6 /home/travis/build/spryker/suite-nonsplit/vendor/propel/propel/src/Propel/Runtime/ActiveQuery/ModelCriteria.php(1271): Propel\\Runtime\\ActiveQuery\\ModelCriteria->doSelect(Object(Propel\\Runtime\\Connection\\ConnectionWrapper))

#7 /home/travis/build/spryker/suite-nonsplit/vendor/spryker/spryker/Bundles/Oms/src/Spryker/Zed/Oms/Persistence/OmsRepository.php(111): Propel\\Runtime\\ActiveQuery\\ModelCriteria->findOne()
```

**Comment by dereuromark** [comment]
We also have the problem that quite a few modules require changes like
```diff
-            ->select([static::KEY_ABSTRACT_PRODUCT_ID, static::KEY_MERCHANT_NAME, static::KEY_MERCHANT_REFERENCE])
+            ->select([SpyProductAbstractTableMap::COL_ID_PRODUCT_ABSTRACT, SpyMerchantTableMap::COL_NAME, SpyMerchantTableMap::COL_MERCHANT_REFERENCE,
```
in `MerchantProductOfferSearchRepository extends AbstractRepository` etc

This will create some costly issues for us that we currently need to investigate how we could shim this to also support previous version of propel still at the same time.

**Comment by mringler** [comment]
Interesting. The first one seems to be the well-known issue with non-aggregated columns not in GROUP BY. Weird that you are seeing those now, I am not aware of any changes to that area since your last test. If you can post the Propel query, and maybe the generated SQL, I might find something.
You are using Postgres, right? The GROUP BY statement is build by PgsqlAdapter::getGroupBy(), which should be called in SelectQueryBuilder line 63ff:
```php
        $groupBy = $this->adapter->getGroupBy($this->criteria);
        if ($groupBy) {
            $this->criteria->replaceNames($groupBy);
            $sqlClauses[] = $groupBy;
        }
```
I am pretty sure that this behavior is tested, so it would be weird if this is not working. But possible, of course. Maybe looking at the queries helps to clear that up.

The second one I don't understand at all, but it looks like you had constants with the column names in your `MerchantProductOfferSearchRepository`, and those were removed, so now you need to retrieve them from the table map. I am not aware of a place where propel generates column aliases with a name like `KEY_`, and if you look at it, it seems like the column names do not always match the name in the variable, i.e. `KEY_MERCHANT_NAME` vs `COL_NAME`, but `KEY_MERCHANT_REFERENCE` vs `COL_MERCHANT_REFERENCE`. My first guess is that something changed in your `MerchantProductOfferSearchRepository`, not in Propel. But it is obviously hard to determine without knowing the Repository classes.
