### ISSUE TITLE
Archivable Behavior Not Compatible with Timestampable

### ISSUE THREAD

**Issue by goreillysydcon** [propelorm/Propel2#924]
When you try to delete a record that has both the archivable and timestampable behavior an exception is thrown.

```
::1:49764 [200]: ~~~~~ - Uncaught exception 'Propel\Runtime\Exception\BadMethodCallException' with message 'Call to undefined method: setcreated_at.' in ~~~~~_archive.php:1194
Stack trace:
#0 ~~~~~model.php(1219): Base\model_archive->__call('setcreated_at', Array)
#1 ~~~~~model.php(1219): model_archive->setcreated_at(Object(DateTime))
#2 ~~~~~model.php(1667): Base\model->copyInto(Object(model_archive), false, false)
#3 ~~~~~modelQuery.php(703): Base\model->archive(Object(Propel\Runtime\Connection\ProfilerConnectionWrapper))
```

I guess it's happening because the archive code generated includes these lines in the base record class:
```php
public function copyInto($copyObj, $deepCopy = false, $makeNew = true)
    {
        ...
        $copyObj->setcreated_at($this->getcreated_at());
        $copyObj->setupdated_at($this->getupdated_at());
```

However setcreated_at isn't defined, only setarchived_at is.

I'm on 2.0.*@dev

**Comment by mjahn** [comment]
A possible workaround is to position the "archivable"-behavior after all other behaviors, so that it can clone the generated columns.

**Comment by dereuromark** [comment]
Is someone able to make a PR here with suggested changes?
